apiVersion : v1
kind : ConfigMap
metadata:
  name : project-backend-user-golang-config-map
data:
  applicationPort : "10002"
  applicationTimeout: "5"

---

apiVersion: v1
kind: Secret
metadata:
  name: project-backend-user-golang-secret
data:
  mysqlHost: cHJvamVjdC1teXNxbA==
  mysqlUsername: cm9vdA==
  mysqlPassword: MTIzNDU=
  mysqlDatabase: dXNlcg==
  mysqlMaxOpenConnection: MTA=
  mysqlMaxIdleConnection: MTA=
  mysqlConnectionMaxLifetime: MTA=
  mysqlConnectionMaxIdletime: MTA=
  redisHost: cHJvamVjdC1yZWRpczo2Mzc5
  redisDatabase: MA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-backend-user-golang
spec:
  selector:
    matchLabels:
      app: project-backend-user-golang
  replicas: 1
  template:
    metadata:
      labels:
        app: project-backend-user-golang
    spec:
      containers:
        - name: project-user
          image: project-user:1.0.0
          ports:
            - containerPort: 10002
          resources:
            requests: 
              cpu: 100m
              memory: 100Mi
            limits: 
              cpu: 200m
              memory: 200Mi
          env:
            - name: APPLICATION_PORT
              valueFrom:
                configMapKeyRef:
                  name: project-backend-user-golang-config-map
                  key: applicationPort
            - name: APPLICATION_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: project-backend-user-golang-config-map
                  key: applicationTimeout
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlHost
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlUsername
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlPassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlDatabase
            - name: MYSQL_MAX_OPEN_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlMaxOpenConnection
            - name: MYSQL_MAX_IDLE_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlMaxIdleConnection
            - name: MYSQL_CONNECTION_MAX_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlConnectionMaxLifetime
            - name: MYSQL_CONNECTION_MAX_IDLETIME
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: mysqlConnectionMaxIdletime
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: redisHost
            - name: REDIS_DATABASE
              valueFrom:
                secretKeyRef:
                  name: project-backend-user-golang-secret
                  key: redisDatabase

---

apiVersion: v1
kind: Service
metadata:
  name: project-backend-user-golang
spec:
  selector:
    app: project-backend-user-golang
  ports:
    - protocol: "TCP"
      port: 10002
      targetPort: 10002
  type: ClusterIP