apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-redis
  template:
    metadata:
      labels:
        app: project-redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      #   volumeMounts:
      #   - name: config
      #     mountPath: /usr/local/etc/redis/redis.conf
      #     subPath: redis.conf
      #   args:
      #   - redis-server
      #   - /usr/local/etc/redis/redis.conf
      # volumes:
      # - name: config
      #   configMap:
      #     name: redis-config
---
apiVersion: v1
kind: Service
metadata:
  name: project-redis
spec:
  # type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      # nodePort: 30379  # Choose a port that is free in your machine
  selector:
    app: project-redis